Blog/config/routes.rb
Rails.application.routes.draw do
  root 'posts#index', as: 'home'
  get 'About' => 'pages#About' , as: 'about'

  resources :posts do
    resources :comments
  end
end

Blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Blog/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

Blog/app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  validates :title, presence:true, length:{minimum:5}
end

Blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Blog/app/controllers/coments_controller.rb
class ComentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(coment_params)
    redirect_to post_path(@post)
  end

  private def coment_params
    params.require(:comment).permit(:username,:Body)
  end
end

Blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(coment_params)
    redirect_to post_path(@post)
  end

  private def coment_params
    params.require(:comment).permit(:username,:Body)
  end
end

Blog/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def About
    @SomeVar = 'SomeVariable'
  end
end

Blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    http_basic_authenticate_with name: "admin", password: "123",
    except: [:index, :show]

    def index
      @post = Post.all
    end

    def new
      @post = Post.new
    end

    def show
      @post = Post.find(params[:id])
    end

    def update
      @post = Post.find(params[:id])
      if(@post.update(post_params))
        redirect_to @post
      else
        render 'edit'
      end
    end

    def destroy
      @post = Post.find(params[:id])
      @post.destroy
      redirect_to posts_path
    end

    def edit
      @post = Post.find(params[:id])
    end

    def create
      #render plain: params[:post].inspect
      @post = Post.new(post_params)

      if(@post.save)
        redirect_to @post
      else
        render 'new'
      end
    end

    private def post_params
      params.require(:post).permit(:title,:body)
    end
end

Blog/app/helpers/application_helper.rb
module ApplicationHelper
end

Blog/app/helpers/coments_helper.rb
module ComentsHelper
end

Blog/app/helpers/comments_helper.rb
module CommentsHelper
end

Blog/app/helpers/pages_helper.rb
module PagesHelper
end

Blog/app/helpers/posts_helper.rb
module PostsHelper
end

Blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'https://getbootstrap.com/docs/4.5/examples/cover/cover.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="D:\RubyProject\Blog\app\views\layouts\application.css">

  </head>

  <body class="text-center">
  <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="masthead mb-auto">
    <div class="inner">
      <h3 class="masthead-brand font-weight-bold">My Simple Blog</h3>
      <nav class="nav nav-masthead justify-content-center">
        <span class="nav-link"><%= link_to "Home", home_path%></span>
        <span class="nav-link"><%= link_to "Posts", new_post_path%></span>
        <span class="nav-link"><%= link_to "Contacts", about_path%></span>
      </nav>
    </div>
  </header>
  <main role="main" class="inner cover">
    <%= yield %>
  </main>
  <footer class="mastfoot mt-auto">
    <div class="inner">
      <p>Blog sample, by <a href="https://www.instagram.com/vanyashelemba/">@Shelemba_Ivan</a>.</p>
      <p>2020</p>
    </div>
  </footer>

  </body>
</html>

Blog/app/views/pages/About.html.erb
<!DOCTYPE html>
<html>
  <body class="text-center">

  <main class="mastfoot mt-auto">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <img height = "400" class="mr-3" src="https://instagram.fudj1-1.fna.fbcdn.net/v/t51.2885-15/e35/s1080x1080/80594113_624647878106050_1372897378902048628_n.jpg?_nc_ht=instagram.fudj1-1.fna.fbcdn.net&_nc_cat=110&_nc_ohc=HYlMa9ZX_f4AX9nbYgr&oh=e7e5f57decfc3a8026c7cd12e26404a6&oe=5EFA36B1" alt="Generic placeholder image">
 <p>Ivan Shelemba PZ-22</p>
  </div>
  <hr color = "#AAA">

  </main>

  </body>
</html>

Blog/app/views/posts/edit.html.erb
<h2>Post editing</h2>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
<p>
  Name<br>
  <%= f.text_field(:title, {:class => 'form-control'}) %>
</p>
<p>
  Text area<br>
  <%= f.text_area(:body, {:class => 'form-control'}) %>
</p>
<p>
  <%= f.submit({:class => 'btn btn-lg btn-secondary'})%>
</p>
<%end%>

Blog/app/views/posts/index.html.erb
<h1> All posts </h1>
<hr color = "#AAA" >
<% @post.each do |post| %>
  <p>
  <div class="container">
      <h3 class="cover-heading"> <%=post.title%> </h3>
      <h3 class="lead"> <%=post.body%> </h3>
      <%=link_to "Show all",post_path(post),:class => 'btn btn-outline-secondary'%>
   </div>
   </p>
   <hr color = "#AAA">
<%end%>

Blog/app/views/posts/new.html.erb
<h2>New post adding</h2>
<%= form_for :post, url: posts_path do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
<p>
  Name<br>
  <%= f.text_field(:title, {:class => 'form-control'}) %>
</p>
<p>
  Text area<br>
  <%= f.text_area(:body, {:class => 'form-control'}) %>
</p>
<p>
  <%= f.submit({:class => 'btn btn-lg btn-secondary'})%>
</p>
<%end%>

Blog/app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<h4><%= @post.body %></h4>
<hr color="#fff">

  <%= link_to "Edit", edit_post_path(@post), :class => 'btn btn-outline-light' %>
  <%= link_to "Delete", post_path(@post),method: :delete, data:{confirm: "Are you sure you want to delete this post?"}, :class => 'btn btn-outline-light' %>
<hr color="#fff">
<div class="container">
<h1> Comments: </h1>
<% @post.comments.each do |comment| %>
  <div class="inner cover">
    <p><strong><%= comment.username %>:</strong> <%= comment.Body %> </p>
  </div>
<%end%>
<hr color="#fff">
<h4>Add comment</h4>
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    Username<br>
    <%= f.text_field(:username, {:class => 'form-control'}) %>
  </p>
  <p>
    Text<br>
    <%= f.text_area(:Body, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.submit("Submit",{:class => 'btn btn-lg btn-secondary'})%>
  </p>
<%end%>
</div>